trigger: none
schedules:
  - cron: "* * * * *"
    displayName: Every minute
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

jobs:
- job: Work
  steps:
  - script: echo $(Build.ArtifactStagingDirectory)
    displayName: 'Run a one-line script'


